/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-06-05 16:09:48 UTC)
 * on 2013-06-18 at 20:48:41 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.regattaendpoint;

/**
 * Service definition for Regattaendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link RegattaendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Regattaendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION == 14,
        "You are currently running with version %s of google-api-client. " +
        "You need version 1.14 of google-api-client to run version " +
        "1.14.2-beta of the  library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://eregatta.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "regattaendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Regattaendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Regattaendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * An accessor for creating requests from the RegattaEndpoint collection.
   *
   * <p>The typical use is:</p>
   * <pre>
   *   {@code Regattaendpoint regattaendpoint = new Regattaendpoint(...);}
   *   {@code Regattaendpoint.RegattaEndpoint.List request = regattaendpoint.regattaEndpoint().list(parameters ...)}
   * </pre>
   *
   * @return the resource collection
   */
  public RegattaEndpoint regattaEndpoint() {
    return new RegattaEndpoint();
  }

  /**
   * The "regattaEndpoint" collection of methods.
   */
  public class RegattaEndpoint {

    /**
     * Create a request for the method "regattaEndpoint.downloadRegattas".
     *
     * This request holds the parameters needed by the the regattaendpoint server.  After setting any
     * optional parameters, call the {@link DownloadRegattas#execute()} method to invoke the remote
     * operation.
     *
     * @return the request
     */
    public DownloadRegattas downloadRegattas() throws java.io.IOException {
      DownloadRegattas result = new DownloadRegattas();
      initialize(result);
      return result;
    }

    public class DownloadRegattas extends RegattaendpointRequest<com.google.api.services.regattaendpoint.model.RegattaCollection> {

      private static final String REST_PATH = "downloadRegattas";

      /**
       * Create a request for the method "regattaEndpoint.downloadRegattas".
       *
       * This request holds the parameters needed by the the regattaendpoint server.  After setting any
       * optional parameters, call the {@link DownloadRegattas#execute()} method to invoke the remote
       * operation. <p> {@link DownloadRegattas#initialize(com.google.api.client.googleapis.services.Abs
       * tractGoogleClientRequest)} must be called to initialize this instance immediately after
       * invoking the constructor. </p>
       *
       * @since 1.13
       */
      protected DownloadRegattas() {
        super(Regattaendpoint.this, "GET", REST_PATH, null, com.google.api.services.regattaendpoint.model.RegattaCollection.class);
      }

      @Override
      public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
        return super.executeUsingHead();
      }

      @Override
      public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
        return super.buildHttpRequestUsingHead();
      }

      @Override
      public DownloadRegattas setAlt(java.lang.String alt) {
        return (DownloadRegattas) super.setAlt(alt);
      }

      @Override
      public DownloadRegattas setFields(java.lang.String fields) {
        return (DownloadRegattas) super.setFields(fields);
      }

      @Override
      public DownloadRegattas setKey(java.lang.String key) {
        return (DownloadRegattas) super.setKey(key);
      }

      @Override
      public DownloadRegattas setOauthToken(java.lang.String oauthToken) {
        return (DownloadRegattas) super.setOauthToken(oauthToken);
      }

      @Override
      public DownloadRegattas setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (DownloadRegattas) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public DownloadRegattas setQuotaUser(java.lang.String quotaUser) {
        return (DownloadRegattas) super.setQuotaUser(quotaUser);
      }

      @Override
      public DownloadRegattas setUserIp(java.lang.String userIp) {
        return (DownloadRegattas) super.setUserIp(userIp);
      }

      @Override
      public DownloadRegattas set(String parameterName, Object value) {
        return (DownloadRegattas) super.set(parameterName, value);
      }
    }

  }

  /**
   * Create a request for the method "getRegatta".
   *
   * This request holds the parameters needed by the the regattaendpoint server.  After setting any
   * optional parameters, call the {@link GetRegatta#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetRegatta getRegatta(java.lang.Long id) throws java.io.IOException {
    GetRegatta result = new GetRegatta(id);
    initialize(result);
    return result;
  }

  public class GetRegatta extends RegattaendpointRequest<com.google.api.services.regattaendpoint.model.Regatta> {

    private static final String REST_PATH = "regatta/{id}";

    /**
     * Create a request for the method "getRegatta".
     *
     * This request holds the parameters needed by the the regattaendpoint server.  After setting any
     * optional parameters, call the {@link GetRegatta#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetRegatta#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetRegatta(java.lang.Long id) {
      super(Regattaendpoint.this, "GET", REST_PATH, null, com.google.api.services.regattaendpoint.model.Regatta.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetRegatta setAlt(java.lang.String alt) {
      return (GetRegatta) super.setAlt(alt);
    }

    @Override
    public GetRegatta setFields(java.lang.String fields) {
      return (GetRegatta) super.setFields(fields);
    }

    @Override
    public GetRegatta setKey(java.lang.String key) {
      return (GetRegatta) super.setKey(key);
    }

    @Override
    public GetRegatta setOauthToken(java.lang.String oauthToken) {
      return (GetRegatta) super.setOauthToken(oauthToken);
    }

    @Override
    public GetRegatta setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetRegatta) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetRegatta setQuotaUser(java.lang.String quotaUser) {
      return (GetRegatta) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetRegatta setUserIp(java.lang.String userIp) {
      return (GetRegatta) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetRegatta setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetRegatta set(String parameterName, Object value) {
      return (GetRegatta) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertRegatta".
   *
   * This request holds the parameters needed by the the regattaendpoint server.  After setting any
   * optional parameters, call the {@link InsertRegatta#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.google.api.services.regattaendpoint.model.Regatta}
   * @return the request
   */
  public InsertRegatta insertRegatta(com.google.api.services.regattaendpoint.model.Regatta content) throws java.io.IOException {
    InsertRegatta result = new InsertRegatta(content);
    initialize(result);
    return result;
  }

  public class InsertRegatta extends RegattaendpointRequest<com.google.api.services.regattaendpoint.model.Regatta> {

    private static final String REST_PATH = "regatta";

    /**
     * Create a request for the method "insertRegatta".
     *
     * This request holds the parameters needed by the the regattaendpoint server.  After setting any
     * optional parameters, call the {@link InsertRegatta#execute()} method to invoke the remote
     * operation. <p> {@link InsertRegatta#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.google.api.services.regattaendpoint.model.Regatta}
     * @since 1.13
     */
    protected InsertRegatta(com.google.api.services.regattaendpoint.model.Regatta content) {
      super(Regattaendpoint.this, "POST", REST_PATH, content, com.google.api.services.regattaendpoint.model.Regatta.class);
    }

    @Override
    public InsertRegatta setAlt(java.lang.String alt) {
      return (InsertRegatta) super.setAlt(alt);
    }

    @Override
    public InsertRegatta setFields(java.lang.String fields) {
      return (InsertRegatta) super.setFields(fields);
    }

    @Override
    public InsertRegatta setKey(java.lang.String key) {
      return (InsertRegatta) super.setKey(key);
    }

    @Override
    public InsertRegatta setOauthToken(java.lang.String oauthToken) {
      return (InsertRegatta) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertRegatta setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertRegatta) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertRegatta setQuotaUser(java.lang.String quotaUser) {
      return (InsertRegatta) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertRegatta setUserIp(java.lang.String userIp) {
      return (InsertRegatta) super.setUserIp(userIp);
    }

    @Override
    public InsertRegatta set(String parameterName, Object value) {
      return (InsertRegatta) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeRegatta".
   *
   * This request holds the parameters needed by the the regattaendpoint server.  After setting any
   * optional parameters, call the {@link RemoveRegatta#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveRegatta removeRegatta(java.lang.Long id) throws java.io.IOException {
    RemoveRegatta result = new RemoveRegatta(id);
    initialize(result);
    return result;
  }

  public class RemoveRegatta extends RegattaendpointRequest<com.google.api.services.regattaendpoint.model.Regatta> {

    private static final String REST_PATH = "regatta/{id}";

    /**
     * Create a request for the method "removeRegatta".
     *
     * This request holds the parameters needed by the the regattaendpoint server.  After setting any
     * optional parameters, call the {@link RemoveRegatta#execute()} method to invoke the remote
     * operation. <p> {@link RemoveRegatta#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveRegatta(java.lang.Long id) {
      super(Regattaendpoint.this, "DELETE", REST_PATH, null, com.google.api.services.regattaendpoint.model.Regatta.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveRegatta setAlt(java.lang.String alt) {
      return (RemoveRegatta) super.setAlt(alt);
    }

    @Override
    public RemoveRegatta setFields(java.lang.String fields) {
      return (RemoveRegatta) super.setFields(fields);
    }

    @Override
    public RemoveRegatta setKey(java.lang.String key) {
      return (RemoveRegatta) super.setKey(key);
    }

    @Override
    public RemoveRegatta setOauthToken(java.lang.String oauthToken) {
      return (RemoveRegatta) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveRegatta setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveRegatta) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveRegatta setQuotaUser(java.lang.String quotaUser) {
      return (RemoveRegatta) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveRegatta setUserIp(java.lang.String userIp) {
      return (RemoveRegatta) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveRegatta setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveRegatta set(String parameterName, Object value) {
      return (RemoveRegatta) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateRegatta".
   *
   * This request holds the parameters needed by the the regattaendpoint server.  After setting any
   * optional parameters, call the {@link UpdateRegatta#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.google.api.services.regattaendpoint.model.Regatta}
   * @return the request
   */
  public UpdateRegatta updateRegatta(com.google.api.services.regattaendpoint.model.Regatta content) throws java.io.IOException {
    UpdateRegatta result = new UpdateRegatta(content);
    initialize(result);
    return result;
  }

  public class UpdateRegatta extends RegattaendpointRequest<com.google.api.services.regattaendpoint.model.Regatta> {

    private static final String REST_PATH = "regatta";

    /**
     * Create a request for the method "updateRegatta".
     *
     * This request holds the parameters needed by the the regattaendpoint server.  After setting any
     * optional parameters, call the {@link UpdateRegatta#execute()} method to invoke the remote
     * operation. <p> {@link UpdateRegatta#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.google.api.services.regattaendpoint.model.Regatta}
     * @since 1.13
     */
    protected UpdateRegatta(com.google.api.services.regattaendpoint.model.Regatta content) {
      super(Regattaendpoint.this, "PUT", REST_PATH, content, com.google.api.services.regattaendpoint.model.Regatta.class);
    }

    @Override
    public UpdateRegatta setAlt(java.lang.String alt) {
      return (UpdateRegatta) super.setAlt(alt);
    }

    @Override
    public UpdateRegatta setFields(java.lang.String fields) {
      return (UpdateRegatta) super.setFields(fields);
    }

    @Override
    public UpdateRegatta setKey(java.lang.String key) {
      return (UpdateRegatta) super.setKey(key);
    }

    @Override
    public UpdateRegatta setOauthToken(java.lang.String oauthToken) {
      return (UpdateRegatta) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateRegatta setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateRegatta) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateRegatta setQuotaUser(java.lang.String quotaUser) {
      return (UpdateRegatta) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateRegatta setUserIp(java.lang.String userIp) {
      return (UpdateRegatta) super.setUserIp(userIp);
    }

    @Override
    public UpdateRegatta set(String parameterName, Object value) {
      return (UpdateRegatta) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Regattaendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Regattaendpoint}. */
    @Override
    public Regattaendpoint build() {
      return new Regattaendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link RegattaendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setRegattaendpointRequestInitializer(
        RegattaendpointRequestInitializer regattaendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(regattaendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
